# Generated by Django 3.2.7 on 2021-09-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_activee',
            new_name='is_active',
        ),
    ]
